---
- name: configure timezone
  command: timedatectl set-timezone America/New_York

- name: disable timesyncd
  command: timedatectl set-ntp off

- name: install required packages
  apt: 
    state: present 
    package: ['unzip', 'ntp', 'apt-transport-https', 'software-properties-common', 'bridge-utils', 'ipvsadm']

- sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

# - sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: 1
#   retries: 3
#   delay: 5

- modprobe:
    name: "{{ item }}" 
    state: present
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool

- name: open access to node's private network interface
  iptables:
    chain: INPUT
    in_interface: enp0s8  
    jump: ACCEPT
    action: insert
    state: present