---
- name: add keys for docker repository
  apt_key: 
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add more keys for docker repository
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
    state: present
    filename: 'docker'

- name: install docker engine
  apt:
    package: docker-ce=18.06.1~ce~3-0~ubuntu
    state: present

# - name: flush iptables
#   iptables:
#     table: nat
#     flush: true

# - name: create bridge
#   openvswitch_bridge:
#     bridge: cbr0
#     state: present

- name: reconfigure docker
  template:
    force: true
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json