---
- name: capture kubernetes join command
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ master_node }}"
  become: true
  run_once: true
  register: join_command

- name: join other nodes
  shell: "{{ join_command.stdout }} && touch .kube.joined"
  args:
    creates: .kube.joined
  when:  master_node != inventory_hostname
  become: true

- name: fix node addr
  template: 
    force: true
    src:  kubelet
    dest: /etc/default/kubelet
  become: true
  notify:
  - restart kubelet
